import { useState } from "react";

export default function ReportsPage() {
  const [reportType, setReportType] = useState("weekly");

  const reports = {
    weekly: {
      title: "Weekly Team Report",
      body: `
Team completed 18 planned tasks this week.
3 items moved to next sprint.
Overall delivery health is stable.
One resource needs bandwidth support.
Productivity improved by 12%.
      `,
    },

    client: {
      title: "Client Status Report",
      body: `
Purchase module workflow completed.
UAT fixes in progress.
Dashboard enhancements started.
Expected milestone closure by Friday.
Awaiting API access from client team.
      `,
    },

    risks: {
      title: "Risk Summary Report",
      body: `
1. ERP API delay may impact integration timeline.
2. One engineer overloaded.
3. Pending UAT signoff from client.
4. Scope change request under review.
      `,
    },

    productivity: {
      title: "Productivity Report",
      body: `
Top performer: Arjun
Average closure rate: 89%
Pending tasks reduced by 15%
Follow-up response rate improved
Lead efficiency score: 93%
      `,
    },
  };

  const current = reports[reportType];

  const printPage = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      <div className="bg-white rounded-xl shadow p-5">
        <h2 className="text-xl font-semibold mb-4">
          Executive Reports Center
        </h2>

        <div className="grid md:grid-cols-4 gap-4">
          <button
            onClick={() => setReportType("weekly")}
            className="bg-blue-600 text-white px-4 py-2 rounded"
          >
            Weekly
          </button>

          <button
            onClick={() => setReportType("client")}
            className="bg-blue-600 text-white px-4 py-2 rounded"
          >
            Client
          </button>

          <button
            onClick={() => setReportType("risks")}
            className="bg-blue-600 text-white px-4 py-2 rounded"
          >
            Risks
          </button>

          <button
            onClick={() => setReportType("productivity")}
            className="bg-blue-600 text-white px-4 py-2 rounded"
          >
            Productivity
          </button>
        </div>
      </div>

      <div className="bg-white rounded-xl shadow p-8 print:shadow-none">
        <div className="flex justify-between items-center mb-6">
          <h3 className="text-2xl font-bold">
            {current.title}
          </h3>

          <button
            onClick={printPage}
            className="bg-green-600 text-white px-4 py-2 rounded print:hidden"
          >
            Print / Save PDF
          </button>
        </div>

        <div className="whitespace-pre-line leading-8 text-gray-700">
          {current.body}
        </div>

        <div className="mt-10 border-t pt-4 text-sm text-gray-500">
          Generated by LeadPilot AI
        </div>
      </div>
    </div>
  );
}