import { useEffect, useState } from "react";

export default function ReportsPage() {
  const [reportType, setReportType] =
    useState("weekly");

  const [reports, setReports] =
    useState(null);

  useEffect(() => {
    loadReports();

    const timer = setInterval(
      loadReports,
      5000
    );

    return () => clearInterval(timer);
  }, []);

  const loadReports = async () => {
    try {
      const res = await fetch(
        "http://127.0.0.1:8000/reports-data"
      );

      const data = await res.json();
      setReports(data);
    } catch (error) {
      console.error(error);
    }
  };

  const printPage = () => {
    window.print();
  };

  if (!reports) {
    return (
      <div className="text-lg font-medium">
        Loading Reports...
      </div>
    );
  }

  const current =
    reports[reportType];

  return (
    <div className="space-y-6">

      {/* Header */}
      <div className="bg-white rounded-xl shadow p-5">

        <h2 className="text-xl font-semibold mb-4">
          Executive Reports Center
        </h2>

        <div className="grid md:grid-cols-4 gap-4">

          <button
            onClick={() =>
              setReportType(
                "weekly"
              )
            }
            className="bg-blue-600 text-white px-4 py-2 rounded"
          >
            Weekly
          </button>

          <button
            onClick={() =>
              setReportType(
                "client"
              )
            }
            className="bg-blue-600 text-white px-4 py-2 rounded"
          >
            Client
          </button>

          <button
            onClick={() =>
              setReportType(
                "risks"
              )
            }
            className="bg-blue-600 text-white px-4 py-2 rounded"
          >
            Risks
          </button>

          <button
            onClick={() =>
              setReportType(
                "productivity"
              )
            }
            className="bg-blue-600 text-white px-4 py-2 rounded"
          >
            Productivity
          </button>

        </div>

      </div>

      {/* Report */}
      <div className="bg-white rounded-xl shadow p-8 print:shadow-none">

        <div className="flex justify-between items-center mb-6">

          <h3 className="text-2xl font-bold">
            {current.title}
          </h3>

          <button
            onClick={
              printPage
            }
            className="bg-green-600 text-white px-4 py-2 rounded print:hidden"
          >
            Print / Save PDF
          </button>

        </div>

        <div className="whitespace-pre-line leading-8 text-gray-700">
          {current.body}
        </div>

        <div className="mt-10 border-t pt-4 text-sm text-gray-500">
          Generated by LeadPilot AI
        </div>

      </div>

    </div>
  );
}